# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:OVJNLiK4StaLOoCzkJMi22ab9YxihXsu2zK0dEg2Z1/45ty49wwG0Yyt6k/X/NaMjkUz/PwtF4/BhuVwuztPa8+smglGVAqMohPfs0mE8tD5cDsFTeRXfD0DYt+NRN09lBE8hxvaPitFi7JoD1+Ylv6ckONY6eWKgDYb/airqa44KoAqkRmMbjV3oeGg2xs1173E/DUhjDSV25DskY2SuZqDFk62rYmFatnQW+thftoaH4wjOA==,iv:9Fyq8IBGa8henp38mS4h5SHE7JVmg/9iiaf69EODezc=,tag:6AasUEXxw9LhsNQbM3NVHQ==,type:str]
sops:
  age:
    - recipient: age10gcvhz5mh2h6lnyu0jvxuzpg7w4j60clqtdsxk40c69l704wvpqsmumatr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWdDaFc2cmhwc1hLSUhC
        OHh3SS9EVGVSMUswR005VmpPdXZWR1BmcXpFCmcxTXJ5L1JSbWpYY2I3SzltRi9y
        M2psYWdENlBzUDViUUZjRVFVWDJnQUkKLS0tIC9KN1lDVDJJSnREZFNoMGozRXMw
        RjdLQXZyY3dhRU5hTlNuVExRL0doWUUKWxHJUyqLMER0ivxGICZfF+DV0ot2sKoy
        pIN5Bh8+jAUcYRlHTEd4C9KqOrrTfJjJUj4+VUyi32lRavf+0EMtig==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yubikey1qwhy4tl638hfxvhr542hdsny7887r2h9u9krvjfelvhya4qf78fmklj2hcj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHBKeXgxUSBBeTVSVW0y
        bURMQXRsb0ltbjhFbElCV2ptOVN6dXJJdTJKSkpmMUozZy82bgpUQ2RVSXk3a1hl
        VGF1V2ZKTHV4SnFRZFp5bFF0L0VuMUlVeCtieUFUcnlJCi0tLSA3UlpaTGlvMmFj
        VmYwL0Jhc3crMXVDcmoyVzJnR2Y4anRUdG5nbjE3Y1FNCg8eNMj4zEMjhNqdYGUa
        4kn/1tdG0erwRyJoiiHrOpXbLS5mTYqEBlQYqdrjx/KO/4L15QQPxzPIAWg1AgOw
        D+s=
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yubikey1qg8vk9mlz7rzfwftvqrwtf6nhlhyevxry6wz45elw4cprnp2cfas28uuzju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDczSXQ3QSBBMU0zT3da
        aFZoeGNUK2Vpa2VJU0ZsSjF4Tms1WDB6K3YxZmt1bGZnYWRHVgpzN3UxQzNuVWNa
        ajM0MkdRaGFxMCtsZUdPc0hIMlJZNXRKQnoreXRvMmRJCi0tLSBrak5uTFJkM25m
        MklzbW1Sbk4wLytoSkNOWEljVUtIUWEvNXNhZkVzUnlnCgxJnAH1cwRjuVA3L7hH
        0x64ghixcDtHUPEygadCTx7mhKqqGKGKmDqgJqAbnWDbYHX9fiMe74wL1XF+I7py
        2/k=
        -----END AGE ENCRYPTED FILE-----
    - recipient: age198hvu2nvgj6zdt6vzfu75pn9uzav7fuyll5fyvd7t799r79f6s5qpr4nv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZnZaT21qRE5pUHdjZTc0
        OUVsMjVTNFdKTHAzdURPRkFvR0hlVWNnazNVCkNGZTlOR2hsNEJLNjUwaUJjcS9h
        ZTNkNnQ2VTQ4OXQ5aTA3eU0ycmFSTU0KLS0tIGlGVDdFaTFNZDRpcnorZlkyRnJx
        bW15NGZiNktPZ0VJUkZFd29Ba08rVmsKmSqImI9jCeyYqpB3rCCw8OLV+TuJNLga
        djpmJ8wblL8B28B5uL+Zc+mRjqWqAD9j1yEZevLvf8YSiCuIZ5GCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T15:21:44Z"
  mac: ENC[AES256_GCM,data:OTgqs6PYUue+xZoj8kN1wz+mneQNEvVV+eXPrZQVJNMWgp96HusmWAjHHLBvHQDQ47ZYddi4JUoRjpAV+KN7vik9QfhbCMwf1FBO5SlWc3dZvEl5W0DUMadMwQEu91T2tUlUEMsfgFdQkdm44+SvSMWTyjVnaNFpsM2vhYz3uNU=,iv:Fq/bXiy3qwXc14zCUYlJsTtu9vkOKqn1reRTDqh1Prs=,tag:Dm8oE+hxGGWmLKOA+PwkdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
