# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7bjVHHWo4ntsJwClF9LxEcoTttDyXo7+s7oflhVKuCFECk9AXRk/yg==,iv:7m0UMyCI0cikQWYX4cKBB6LSYCV6gXXCp+mh2RMTfzc=,tag:xpSNOGo6baTul4vOjGe1+g==,type:str]
sops:
  age:
    - recipient: age10gcvhz5mh2h6lnyu0jvxuzpg7w4j60clqtdsxk40c69l704wvpqsmumatr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMzdBbTlEazN5eGJubmJ3
        R1IxdGlJNkhsYWtGRGxGNDNDamdHdHF3Y1hjCmE0L3hyazFQWDNwMGxYUDRMT3JT
        WU5Cb2hhUy9SV2drRFU1dDJuejkzYncKLS0tIHAzVHVTQmVYWVpDZi81RFBqendF
        WlJJZ3Rna0lxUGNpRHNoYTF6dWdTQnMKnxdINp/F+8ZLGWMf0qcQ03V/xmFJE9Zx
        Xz4Qrg1E5d8MSsrqrBseFIfNEWmPbocVdGF7GVCYORr1aX5gnKrzBQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yubikey1qwhy4tl638hfxvhr542hdsny7887r2h9u9krvjfelvhya4qf78fmklj2hcj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHBKeXgxUSBBbDNNWENk
        bThYUDN1Y2VmUkxOdFd2SWNOY0ZLWDdJd3lVR3NiVVRqaXROOApmcUx2OHczS1hn
        VFlFWkROY3FqeGNhQjY4SWFaMUdOa1JZS1B6a3lXc1FBCi0tLSByZjdSblVTYzRK
        T3NaY2xIRkplRUk4Njkxcnh2ZzlrOXZINmRRNEpYTTJBCsEqeaqslLTlRGvvdY5k
        dUYORmp5F5dJvI4KLu2ruLoB+97rIXV+TGyHR8raBSOp9293H5Yt5J+qucnfxXnS
        Tes=
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yubikey1qg8vk9mlz7rzfwftvqrwtf6nhlhyevxry6wz45elw4cprnp2cfas28uuzju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDczSXQ3QSBBL2VwNFUz
        eXlqenpLNStnenp5Ti9BamJpZkJwNHE5dzI0d2ZnNHpLZnpZYwpZS2hmeitNSndR
        bi95WDA5Sm1SN3BFVlpiUmE0ekFJNUtsamVUdTZIbkR3Ci0tLSB4Nm1kZytFS0Fm
        NUFPMHZVVmdXMGdPMmpGQTdaMktFUTIyL3J1M2RXZ2xRCssNk5Da4ZAKXZBEOqcw
        VmdgWC8lq6BD5tde0Chc6xdHxWVkTHIRS1SqT1fJQO3axLn1mUqzomUU6eltH2DB
        y3s=
        -----END AGE ENCRYPTED FILE-----
    - recipient: age198hvu2nvgj6zdt6vzfu75pn9uzav7fuyll5fyvd7t799r79f6s5qpr4nv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eGFHeE9IWkZTejdrWUo4
        L0JSWjlvR25iMWFHVThsa1RQQ253RzBQMGhzCm95ajJUMjN3dVFvcTkvQTB2aUxs
        QWM2c3p0R1J0dXk1b1huSWhsWEtVZ2MKLS0tIHVFckJSUVprSVhUSWh3aTZEQkJL
        R1Zpc3VKekFadFUrK2lKVXlOZFZXODQKvosPOKFiNxwODkLqy/56aWH8WhruIpzt
        UbDP9dgUYC56Q/aDPU0uLICbecwphBxc1+iOylwo5H1MhMHR64RMWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T15:21:44Z"
  mac: ENC[AES256_GCM,data:htzI1jI9uYqlKzfMRzJhp8D3lfsytilElQGeUyV9YurX24doUHXw2B7uGULYMKcwLhiNpCMDJKQSc8s7kU6zu5cW6fuexrX0j0HqoNEEEnIMvoYGrXQjMsYjm+5X9PLSH+MHVSBaBjp2T8YDS3iNlPG32KRH8LY1CTyuM+RKVi0=,iv:b5fqYLzokUYEEAA7EoFcr8kuuklArXQJ+tT7IOfQ6TU=,tag:WtykGzd9QCgoB81tXCZcOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
