---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
spec:
  name: backup-daily
  cron: '0 2 * * *'
  task: backup
  retain: 3  # Longer-term retention is handled on backup target
  concurrency: 1

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-6h
spec:
  name: snapshot-6h
  cron: "0 */6 * * *"
  task: "snapshot"
  retain: 8  # 2 days
  concurrency: 2
