---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  recurringJobSelector: '[ { "name": "snapshot-6h", "isGroup": false }, { "name": "backup-daily", "isGroup": false } ]'
