---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-direct
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "${SECRET_NFS_SERVER}/${SECRET_NFS_STORAGE_PATH}#gitea#"
    volumeAttributes:
      server: "${SECRET_NFS_SERVER}"
      share: "${SECRET_NFS_STORAGE_PATH}/gitea"
