---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-direct
provisioner: nfs.csi.k8s.io
parameters:
  server: "${SECRET_NFS_SERVER}"
  share: "${SECRET_NFS_STORAGE_PATH}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
