apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KGErxPwuSvn0,iv:n9Ka3f0Q1v8Xx4RPfiidoCROsfGcEsRFXd/34RFO3YA=,tag:7rYgAy6Cctnrs2bC6ME4Yw==,type:str]
sops:
    age:
        - recipient: age10gcvhz5mh2h6lnyu0jvxuzpg7w4j60clqtdsxk40c69l704wvpqsmumatr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUGxDNnFoTGRlWVRySnZj
            dnRNcU9QZTJSRUMvUUtzUGpiR0N4d1YvNFVZCjNEYk0xVmJWYklnTjRpN21nTVYr
            VGt4UFhPR1VIVERKT0FDV3FxL1E2K3cKLS0tIFNVKzh3UmNuMWFXRW9pUkcxOXNW
            c0pvbnIrdSs2N1UwWXJieEdXdHYzVmsK80WyyrCNJvzR/3RFIbiBZHl7ZuaryXxh
            U3ravH6s1nB/rMdZ3hXYMnhRCDhj/zDHBlcdzN8Fl+eshg5pm1CQDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwhy4tl638hfxvhr542hdsny7887r2h9u9krvjfelvhya4qf78fmklj2hcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHBKeXgxUSBBMC9xRitW
            OG9pejFQMEQvSEZ2UmpERVY4eEZqNjhRdlcyZ1hCaEdmMU5UUwpxMVNyNXhkdFli
            aW84U3dMa29Rc3lTcUhOS3prZkZEOVl5TlRjRXp2VjQ4Ci0tLSBqQkcxWERYaFdp
            WHczdWpLWklUWjd1b1NreW9RSVAxNjNxOXU2RW1SWmpFChFd5zIxAaKutzJRyMEM
            +kfOgnyxHHwxHpp1/UMDMr0cHtsgLOA1TcH1UgItK+Ec3eoLeT3R/yfcqbTy7Zux
            P3Q=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg8vk9mlz7rzfwftvqrwtf6nhlhyevxry6wz45elw4cprnp2cfas28uuzju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDczSXQ3QSBBNzNFQnpG
            OHN0NHpaemVNOFRHb21pUFVTQ2VOdUlRNUJVQlJodTBrQUF2awp3dlM0MWtWdHJP
            TmtmRFdQMmZRTVFZQW51ZHhoVnhKTUlGc2t0c1ZBdEdnCi0tLSBZM1JoS3V5eXFF
            c3V4ZkVxT1daaGVqWnRudlg5WWM2N28zcDlYYWRTWkVVCp3ysYwBJqQLmoKCJLAm
            9H+LYOVd+xOrZFWw9G3WHi83Wx7rzuILLSKP8jLIB5MmQYpc1GB9NsZUgoVT+0FY
            U94=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age198hvu2nvgj6zdt6vzfu75pn9uzav7fuyll5fyvd7t799r79f6s5qpr4nv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZTRyU3pSSnIyZmNxZkJE
            MDZ1WlkrQ05TMGFaNjRrazFab1g4Smc4ZnhRCndaNmFJR0UxL05NeXI0emlmbWJS
            TnpyOTNhL2lOT0NDbGVJUU92NkpNRU0KLS0tIDRlcEJrWFlmRE84eUxZMis4dUpY
            b2h2c1g0dndHVzBEcExXSnVXaUNxSEEKn7wB2ZdU/A6ro+Z7o91ty2Nq+22lLvgq
            6sRGnmjnblxfbOAZ5cBKZGfIzPi+qF1UkbY/i6ptIqDjUcX8utYbyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T16:40:58Z"
    mac: ENC[AES256_GCM,data:/GmTSCZyttIdj+Ybfak0jUtx+9TQyGMacFfOGUaUWKXoHtYMtol/3IZbDEpfkhlYpHjwfN9msxjUtc5+usQJTgejyOMcKKo3CckO6IOMhA3ssbSoLLerCCf9M56mYwMIszVwIeynbchvxiQ4wZKohkmF23jXoTisSI9GOv3AON4=,iv:Dfs3KsQUoOUI2U5QYAlZjW+4eNVkxuNVKzr9obgIa7M=,tag:SYViWCNFpEOapSbJvPKbrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
