apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
stringData:
    SECRET_GITEA_SECRET_KEY: ENC[AES256_GCM,data:vzUkjQJ4T/1q9U/WezTxuJkP5HjZ8pKw4VTyfyg6uaGf3IJWE86CwHrZK2o=,iv:ekf192Q1gfX53ssMcbXNpX47IEmlux45lLb+axYfVbg=,tag:YQoQ3npr33ezScDeiYWGTg==,type:str]
    SECRET_GITEA_PG_PASSWORD: ENC[AES256_GCM,data:sqYnijXG59k4QyAsdYcunGtQY1kpx3fUu9hegLs55dPdEEFSj5237v1Xp+o=,iv:gHYF9yvw8kGqSll76CbH/HjvPrj1NCtqQPopoPGsthA=,tag:e9+OAqckzk6+PxECOpi61Q==,type:str]
    SECRET_GITEA_REDIS_PASSWORD: ENC[AES256_GCM,data:2ftPlH81HpD7GI2GDTX+dt+ltRUMAS8HzVk2lu4smVClcOTLq0h7oMcCC+8=,iv:sw2FxPeCDFGoCay3yJ74ylV93mC8QWZYTta8q9+7XgE=,tag:fz5g/iRKyK5EZdPaIa74kQ==,type:str]
sops:
    age:
        - recipient: age10gcvhz5mh2h6lnyu0jvxuzpg7w4j60clqtdsxk40c69l704wvpqsmumatr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZHYxalN6bzB5eDBNUXhx
            Z1lEYlNnRWUwRitHbEdWdHVxRUR6WFdsK2lrClA1TmF4Z2tnbk82eFZlWGhYSFJl
            RGtyblNvWUwzdXlsVUxPcmkyTnFWZ1kKLS0tIEZJdDEreGRrOXpBeFVoZk1vbDQ0
            Z2M3SzYwQ2x1ZXhyRnE2d0pBL1hiZzAK7+lLmolRTn8BE2d5RjmJ7hK3AJA6AcG2
            Lt3PAK/Qq8LRbiplVIfZHwQj1gFBKbarNinfTCgszUcz35Bshm4Ghw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwhy4tl638hfxvhr542hdsny7887r2h9u9krvjfelvhya4qf78fmklj2hcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHBKeXgxUSBBa1JNVVFj
            TnR0SkVBMWxiNWt1UE5uaGQ4cSt2bElaR1g4dzdKMGFjVEYwegpTTWU0eDl2eFdw
            eGx5RVZTd05VMktRaXJkSXZCRlA3ejhnVHpPVUtQMHVBCi0tLSBEb1ZKNnpMMjd5
            TEJHYm1TdzVzVjREZWhBR1BzN1FVL3RmMmJ5SWxBSEhrCuP64TE7NLKOOnZJJYEz
            ZiiqvNEyS2nPs93X7V+zLk4+ea8cbUS8NHH0IsH34krNK/aeF/BtlEjILF+XUn9n
            /w8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg8vk9mlz7rzfwftvqrwtf6nhlhyevxry6wz45elw4cprnp2cfas28uuzju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDczSXQ3QSBBbnVmZGtu
            aHE5R0M5TmhpR3A0OGFyYjZMSXgrY1VBc0VzZFlubnBSbDNaZQpRdk1IaVQ4dzdl
            TzdOSzdYM2ZneDgzZkhYUGo4bmp6djY5Wk4zVzRMZEVVCi0tLSBnREcrZXNPNnc1
            d2s5UjlWUFhEdmdManpLazIxYXlDaDZWNXBEaE8vZEFjCk6g4ljBKTeSVXhlymhj
            lihvbft5mJH0pWVAJNTTNMjjxOA16geJrPtVReX3v2+mUktQuluQCo9hkZynmBsj
            pfk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age198hvu2nvgj6zdt6vzfu75pn9uzav7fuyll5fyvd7t799r79f6s5qpr4nv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Mk1wejBWcm9rNFZ2Y01n
            TDFXODBEZkhQaTlaaUZHSFJLakREQmZ3VkZzCkRIUUZPV0RsUmZvcGVWdGpoOEFP
            bTk5NTlzR1VpR052bGE5MjZVMlcxL0EKLS0tIDNpaVFsZnJiOVRNTGM2cmt4Q3pq
            b2NUbWZ5WG4rTkc2Rkh4Skw3OVhPT1kKdrZtoAGL9bozQgV8ZoSH9issKWZb7pKm
            5Kq4VaM6Z2JqIEroKaYEhQQ/VJO/fLozEQIcgwyG5wi1iCs9lNS2Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T13:42:29Z"
    mac: ENC[AES256_GCM,data:mUEcLMsVwyHbDxZ1vFUDZUJ9zQICm9vZwCiE/q0l2g/kiIXIOusbgBPSYWzrK+HOnrBr16yKQaIS14II3JuNI8kVUalQ1ewdTSNkYUDKWsTlruxqaNa/vbFNq2cUSMOL1g0uPjSBBRVlnn+12pkpM6R5EpBw1J52P8s/s1IbwLc=,iv:M3mFWeUQ9GpgX8Jxk2XtfeJDy6qZ4eNo3qCum6oZTsw=,tag:efSnZ1ff/056Ue0lz0/beg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.1
